dist: xenial
language: rust
rust:
  - nightly
  - beta
  - stable
before_install:
  - sudo apt-get update
  - sudo apt-get install libsoup2.4-dev -y
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    make regen_check;
    fi
  - ./check_init_asserts
  - cargo build
  - cargo build --features="v2_68"