[options]
girs_dir = "gir-files"
library = "Soup"
version = "2.4"
work_mode = "normal"
target_path = "."
generate_safety_asserts = true
single_version_file = true

external_libraries = [
    "Gio"
]

generate = [
	"Soup.Address",
	"Soup.Auth",
	"Soup.AuthBasic",
	"Soup.AuthDigest",
	"Soup.AuthDomain",
	"Soup.AuthDomainBasic",
	"Soup.AuthDomainDigest",
	"Soup.AuthManager",
	"Soup.AuthNTLM",
	"Soup.AuthNegotiate",
	"Soup.Cache",
	"Soup.ContentDecoder",
	"Soup.ContentSniffer",
	"Soup.CookieJar",
	"Soup.CookieJarDB",
	"Soup.CookieJarText",
	"Soup.HSTSEnforcer",
	"Soup.HSTSEnforcerDB",
	"Soup.Logger",
	"Soup.Message",
	"Soup.MultipartInputStream",
	"Soup.ProxyResolverDefault",
	"Soup.Request",
	"Soup.RequestData",
	"Soup.RequestFile",
	"Soup.RequestHTTP",
	"Soup.Requester",
	"Soup.Server",
	"Soup.Session",
	"Soup.SessionAsync",
	"Soup.SessionSync",
	"Soup.Socket",
	"Soup.WebsocketConnection",
	"Soup.WebsocketExtension",
	"Soup.WebsocketExtensionDeflate",
	"Soup.WebsocketExtensionManager",
	"Soup.AddressFamily",
	"Soup.CacheResponse",
	"Soup.CacheType",
	"Soup.ConnectionState",
	"Soup.CookieJarAcceptPolicy",
	"Soup.DateFormat",
	"Soup.Encoding",
	"Soup.HTTPVersion",
	"Soup.KnownStatusCode",
	"Soup.LoggerLogLevel",
	"Soup.MemoryUse",
	"Soup.MessageHeadersType",
	"Soup.MessagePriority",
	"Soup.RequestError",
	"Soup.RequesterError",
	"Soup.SocketIOStatus",
	"Soup.Status",
	"Soup.TLDError",
	"Soup.WebsocketCloseCode",
	"Soup.WebsocketConnectionType",
	"Soup.WebsocketDataType",
	"Soup.WebsocketError",
	"Soup.WebsocketState",
	"Soup.XMLRPCError",
	"Soup.XMLRPCFault",
	"Soup.URI"
]

manual = [
	"Gio.InputStream",
	"Gio.Cancellable",
	"Gio.ProxyResolver",
	"GLib.Bytes",
	"GLib.Data",
	"GLib.DestroyNotify",
	"GLib.Error",
	"GLib.HashTable",
	"GLib.IOChannel",
	"GLib.IOCondition",
	"GLib.IOFunc",
	"GLib.List",
	"GLib.MainContext",
	"GLib.PtrArray",
	"GLib.Quark",
	"GLib.SList",
	"GLib.Source",
	"GLib.SourceFunc",
	"GLib.String",
	"GLib.TimeVal",
	"GLib.Variant",
	"GObject.Object"
]