[options]
girs_dir = "gir-files"
library = "Soup"
version = "2.4"
work_mode = "normal"
target_path = "."
generate_safety_asserts = true
single_version_file = true

external_libraries = [
    "Gio"
]

generate = [
	# "Soup.Address",
	"Soup.Auth",
	"Soup.AuthBasic",
	"Soup.AuthDigest",
	# "Soup.AuthDomain",
	# "Soup.AuthDomainBasic",
	# "Soup.AuthDomainDigest",
	"Soup.AuthManager",
	"Soup.AuthNTLM",
	"Soup.AuthNegotiate",
	# "Soup.Buffer",
	"Soup.Cache",
	"Soup.ContentDecoder",
	"Soup.ContentSniffer",
	"Soup.CookieJarDB",
	"Soup.CookieJarText",
	# "Soup.Date",
	"Soup.HSTSEnforcer",
	"Soup.HSTSEnforcerDB",
	# "Soup.Logger",
	"Soup.Message",
	"Soup.MultipartInputStream",
	"Soup.ProxyResolverDefault",
	"Soup.Request",
	# "Soup.RequestData",
	# "Soup.RequestFile",
	"Soup.RequestHTTP",
	"Soup.Requester",
	"Soup.Server",
	# "Soup.Session",
	# "Soup.SessionAsync",
	# "Soup.SessionSync",
	# "Soup.Socket",
	# "Soup.TLDError",
	"Soup.AddressFamily",
	"Soup.CacheResponse",
	"Soup.CacheType",
	"Soup.ConnectionState",
	"Soup.CookieJarAcceptPolicy",
	"Soup.DateFormat",
	"Soup.Encoding",
	"Soup.HTTPVersion",
	"Soup.KnownStatusCode",
	"Soup.LoggerLogLevel",
	"Soup.MemoryUse",
	"Soup.MessageHeaders",
	"Soup.MessageHeadersType",
	"Soup.MessagePriority",
	"Soup.RequestError",
	"Soup.RequesterError",
	"Soup.SocketIOStatus",
	"Soup.Status",
	"Soup.WebsocketCloseCode",
	"Soup.WebsocketConnectionType",
	"Soup.WebsocketDataType",
	"Soup.WebsocketError",
	# "Soup.WebsocketExtension",
	# "Soup.WebsocketExtensionDeflate",
	# "Soup.WebsocketExtensionManager",
	"Soup.WebsocketState",
	"Soup.XMLRPCError",
	"Soup.XMLRPCFault",
	"Soup.Cacheability",
	"Soup.Expectation",
	"Soup.MessageFlags",
	"Soup.ServerListenOptions"
]

manual = [
	"Gio.InputStream",
	"Gio.Cancellable",
	"Gio.ProxyResolver",
	"Gio.TlsCertificate",
	"Gio.TlsCertificateFlags",
	"GLib.Bytes",
	"GLib.Data",
	"GLib.DestroyNotify",
	"GLib.Error",
	"GLib.HashTable",
	"GLib.IOChannel",
	"GLib.IOCondition",
	"GLib.IOFunc",
	"GLib.List",
	"GLib.MainContext",
	"GLib.PtrArray",
	"GLib.Quark",
	"GLib.SList",
	"GLib.Source",
	"GLib.SourceFunc",
	"GLib.String",
	"GLib.TimeVal",
	"GLib.Variant",
	"GObject.Object"
]

[[object]]
name="Soup.Socket"
status = "generate"
    [[object.function]]
    name = "write"
    ignore = true
	[[object.function]]
    name = "read"
    ignore = true

[[object]]
name="Soup.Logger"
status = "generate"
    [[object.function]]
    name = "set_printer"
    ignore = true

[[object]]
name="Soup.RequestData"
status = "generate"
version = "v2_42"

[[object]]
name="Soup.RequestFile"
status = "generate"
version = "v2_42"

[[object]]
name="Soup.MessageBody"
status = "generate"
    [[object.function]]
    name = "append"
    ignore = true

[[object]]
name="Soup.URI"
status = "generate"
    [[object.function]]
    name = "equal"
	ignore= true
	[[object.function]]
	name="host_equal"
	ignore=true
	[[object.function]]
	name="host_hash"
	ignore=true

[[object]]
name="Soup.Cookie"
status = "generate"
    [[object.function]]
    name = "equal"
	ignore= true

[[object]]
name="Soup.CookieJar"
status = "generate"
    [[object.function]]
    name = "add_cookie"
	ignore= true
    [[object.function]]
    name = "add_cookie_with_first_party"
	ignore= true

[[object]]
name="Soup.Address"
status="generate"
	[[object.function]]
	name = "equal_by_name"
	ignore = true
	[[object.function]]
	name = "equal_by_ip"
	ignore = true
	[[object.function]]
	name = "hash_by_ip"
	ignore = true
	[[object.function]]
	name = "hash_by_name"
	ignore = true

[[object]]
name="Soup.WebsocketConnection"
status="generate"
	[[object.function]]
	name = "send_binary"
	ignore = true