// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use soup_sys;
use std::fmt;
use Auth;

glib_wrapper! {
    pub struct AuthDigest(Object<soup_sys::SoupAuthDigest, AuthDigestClass>) @extends Auth;

    match fn {
        get_type => || soup_sys::soup_auth_digest_get_type(),
    }
}

impl AuthDigest {}

impl fmt::Display for AuthDigest {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "AuthDigest")
    }
}
