// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::GString;
use glib::StaticType;
use glib::Value;
use glib_sys;
use gobject_sys;
use soup_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib_wrapper! {
    pub struct AuthDomainDigest(Object<soup_sys::SoupAuthDomainDigest, soup_sys::SoupAuthDomainDigestClass, AuthDomainDigestClass>);

    match fn {
        get_type => || soup_sys::soup_auth_domain_digest_get_type(),
    }
}

impl AuthDomainDigest {
    //pub fn new(optname1: &str, : /*Unknown conversion*//*Unimplemented*/Fundamental: VarArgs) -> AuthDomainDigest {
    //    unsafe { TODO: call soup_sys:soup_auth_domain_digest_new() }
    //}

    pub fn encode_password(username: &str, realm: &str, password: &str) -> Option<GString> {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(soup_sys::soup_auth_domain_digest_encode_password(username.to_glib_none().0, realm.to_glib_none().0, password.to_glib_none().0))
        }
    }
}

pub const NONE_AUTH_DOMAIN_DIGEST: Option<&AuthDomainDigest> = None;

pub trait AuthDomainDigestExt: 'static {
    fn get_property_auth_callback(&self) -> Fn(&AuthDomainDigest, &Message, &str) -> Option<String> + 'static;

    fn set_property_auth_callback(&self, auth_callback: Fn(&AuthDomainDigest, &Message, &str) -> Option<String> + 'static);

    //fn get_property_auth_data(&self) -> /*Unimplemented*/Fundamental: Pointer;

    //fn set_property_auth_data(&self, auth_data: /*Unimplemented*/Fundamental: Pointer);

    fn connect_property_auth_callback_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_auth_data_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<AuthDomainDigest>> AuthDomainDigestExt for O {
    fn get_property_auth_callback(&self) -> Fn(&AuthDomainDigest, &Message, &str) -> Option<String> + 'static {
        unsafe {
            let mut value = Value::from_type(<Fn(&AuthDomainDigest, &Message, &str) -> Option<String> + 'static as StaticType>::static_type());
            gobject_sys::g_object_get_property(self.to_glib_none().0 as *mut gobject_sys::GObject, b"auth-callback\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `auth-callback` getter").unwrap()
        }
    }

    fn set_property_auth_callback(&self, auth_callback: Fn(&AuthDomainDigest, &Message, &str) -> Option<String> + 'static) {
        unsafe {
            gobject_sys::g_object_set_property(self.to_glib_none().0 as *mut gobject_sys::GObject, b"auth-callback\0".as_ptr() as *const _, Value::from(&auth_callback).to_glib_none().0);
        }
    }

    //fn get_property_auth_data(&self) -> /*Unimplemented*/Fundamental: Pointer {
    //    unsafe {
    //        let mut value = Value::from_type(</*Unknown type*/ as StaticType>::static_type());
    //        gobject_sys::g_object_get_property(self.to_glib_none().0 as *mut gobject_sys::GObject, b"auth-data\0".as_ptr() as *const _, value.to_glib_none_mut().0);
    //        value.get().expect("Return Value for property `auth-data` getter").unwrap()
    //    }
    //}

    //fn set_property_auth_data(&self, auth_data: /*Unimplemented*/Fundamental: Pointer) {
    //    unsafe {
    //        gobject_sys::g_object_set_property(self.to_glib_none().0 as *mut gobject_sys::GObject, b"auth-data\0".as_ptr() as *const _, Value::from(&auth_data).to_glib_none().0);
    //    }
    //}

    fn connect_property_auth_callback_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_auth_callback_trampoline<P, F: Fn(&P) + 'static>(this: *mut soup_sys::SoupAuthDomainDigest, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<AuthDomainDigest>
        {
            let f: &F = &*(f as *const F);
            f(&AuthDomainDigest::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::auth-callback\0".as_ptr() as *const _,
                Some(transmute(notify_auth_callback_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }

    fn connect_property_auth_data_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_auth_data_trampoline<P, F: Fn(&P) + 'static>(this: *mut soup_sys::SoupAuthDomainDigest, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<AuthDomainDigest>
        {
            let f: &F = &*(f as *const F);
            f(&AuthDomainDigest::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::auth-data\0".as_ptr() as *const _,
                Some(transmute(notify_auth_data_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for AuthDomainDigest {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "AuthDomainDigest")
    }
}
