// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use soup_sys;
use std::fmt;
use Auth;

glib_wrapper! {
    pub struct AuthBasic(Object<soup_sys::SoupAuthBasic, AuthBasicClass>) @extends Auth;

    match fn {
        get_type => || soup_sys::soup_auth_basic_get_type(),
    }
}

impl AuthBasic {}

impl fmt::Display for AuthBasic {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "AuthBasic")
    }
}
