// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use soup_sys;
use std::fmt;
use WebsocketExtension;

glib_wrapper! {
    pub struct WebsocketExtensionDeflate(Object<soup_sys::SoupWebsocketExtensionDeflate, soup_sys::SoupWebsocketExtensionDeflateClass, WebsocketExtensionDeflateClass>) @extends WebsocketExtension;

    match fn {
        get_type => || soup_sys::soup_websocket_extension_deflate_get_type(),
    }
}

impl WebsocketExtensionDeflate {}

pub const NONE_WEBSOCKET_EXTENSION_DEFLATE: Option<&WebsocketExtensionDeflate> = None;

impl fmt::Display for WebsocketExtensionDeflate {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "WebsocketExtensionDeflate")
    }
}
