// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use soup_sys;
use std::fmt;

glib_wrapper! {
    pub struct WebsocketExtensionManager(Object<soup_sys::SoupWebsocketExtensionManager, soup_sys::SoupWebsocketExtensionManagerClass, WebsocketExtensionManagerClass>);

    match fn {
        get_type => || soup_sys::soup_websocket_extension_manager_get_type(),
    }
}

impl WebsocketExtensionManager {}

pub const NONE_WEBSOCKET_EXTENSION_MANAGER: Option<&WebsocketExtensionManager> = None;

impl fmt::Display for WebsocketExtensionManager {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "WebsocketExtensionManager")
    }
}
